In [1]:
import pandas as pd

In [26]:
df = pd.read_csv("csv/description-no_description_image__hot_focus-0.8-temperature-us.amazon.nova-premier-v1_0.csv")
df.head(1)

,id,nombre,descripcion_original,descripcion_generada
0,4186694,Termo Critter,¡Haz que la hidratación sea divertida con el T...,"Descubre el Termo Critter de Hot Focus, el com..."

In [28]:
out = pd.DataFrame({})

In [29]:
out["generated_description"] = df["descripcion_generada"]
out["product"] = df["id"]
out["model"] = 2

In [30]:
out["condition"] = 2

In [31]:
out.head()

,generated_description,product,model,condition
0,"Descubre el Termo Critter de Hot Focus, el com...",4186694,2,2
1,Descubre el encantador Estuche con Lapicero Ho...,4186693,2,2
2,Este encantador vaso osito de goma con sorbete...,4186695,2,2
3,Descubre la magia de la creatividad con la Tab...,4186698,2,2
4,Descubre la magia de las aventuras diarias con...,4184319,2,2

In [32]:
out.to_csv("premier-2.csv", index=False)