In [47]:
import pandas as pd

In [48]:
df = pd.read_csv("csv/description-prompt_meta_seo_v2_0.8-us.amazon.nova-premier-v1_0.csv")
df.head(1)

,id,nombre,descripcion_original,descripcion_generada
0,4186694,Termo Critter,¡Haz que la hidratación sea divertida con el T...,META TÍTULO: Termo Critter Hot Focus: Diseño I...

In [50]:
out = pd.DataFrame({})

In [51]:
out["generated_description"] = df["descripcion_generada"]
out["product"] = df["id"]
out["model"] = 2

In [52]:
out["condition"] = 3

In [53]:
out.head()

,generated_description,product,model,condition
0,META TÍTULO: Termo Critter Hot Focus: Diseño I...,4186694,2,3
1,META TÍTULO: Estuche Lapicero Hot Focus: Diver...,4186693,2,3
2,META TÍTULO: Vaso Osito Goma 600ml - Diseño Pe...,4186695,2,3
3,META TÍTULO: Tableta para Dibujar Hot Focus 8....,4186698,2,3
4,META TÍTULO: Lonchera Mariposa Morada Hot Focu...,4184319,2,3

In [54]:
out.to_csv("premier-3.csv", index=False)